-- SiteOrders - Order Workflow V2
-- Consolidated migration for the feature/order-workflow-v2 branch.
-- Compatible with the existing SiteOrders schema; existing pedidos and pedido_items are preserved.

begin;

-- Roles and workflow columns -------------------------------------------------
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
check (role = any (array['admin'::text,'encargado'::text,'supervisor'::text,'store'::text]));

alter table public.pedidos
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists requested_for uuid references public.profiles(id) on delete set null,
  add column if not exists created_by_name_snapshot text,
  add column if not exists receipt_confirmed_by uuid references public.profiles(id) on delete set null,
  add column if not exists receipt_confirmed_at timestamptz;

update public.pedidos set
  created_by=coalesce(created_by,user_id),
  requested_for=coalesce(requested_for,user_id),
  created_by_name_snapshot=coalesce(created_by_name_snapshot,requested_by_name)
where created_by is null or requested_for is null or created_by_name_snapshot is null;

alter table public.pedido_items
  add column if not exists quantity_received numeric not null default 0,
  add column if not exists receipt_observation text,
  add column if not exists received_by uuid references public.profiles(id) on delete set null,
  add column if not exists received_at timestamptz;

alter table public.pedido_items drop constraint if exists pedido_items_quantity_received_nonnegative;
alter table public.pedido_items add constraint pedido_items_quantity_received_nonnegative check(quantity_received>=0);

alter table public.pedidos drop constraint if exists pedidos_status_check;
alter table public.pedidos add constraint pedidos_status_check
check(status = any(array['pending'::text,'approved'::text,'awaiting_receipt'::text,'partial'::text,'completed'::text,'rejected'::text,'delivered'::text]));

drop index if exists public.uq_pedidos_project_sequence;

-- Project assignments -------------------------------------------------------
create table if not exists public.project_members(
  project_id integer not null references public.proyectos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(project_id,user_id)
);
create index if not exists idx_project_members_user_id on public.project_members(user_id);
alter table public.project_members enable row level security;
grant select,insert,delete on public.project_members to authenticated;

-- Dispatch / receipt --------------------------------------------------------
create table if not exists public.order_dispatches(
  id bigint generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id) on delete cascade,
  dispatched_by uuid not null references public.profiles(id) on delete restrict,
  note text,
  created_at timestamptz not null default now(),
  receipt_confirmed_by uuid references public.profiles(id) on delete set null,
  receipt_confirmed_at timestamptz
);

create table if not exists public.order_dispatch_items(
  id bigint generated by default as identity primary key,
  dispatch_id bigint not null references public.order_dispatches(id) on delete cascade,
  pedido_item_id integer not null references public.pedido_items(id) on delete cascade,
  material_id integer references public.materiales(id) on delete restrict,
  quantity_dispatched numeric not null check(quantity_dispatched>0),
  quantity_received numeric not null default 0 check(quantity_received>=0),
  receipt_observation text,
  received_by uuid references public.profiles(id) on delete set null,
  received_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_order_dispatches_pedido on public.order_dispatches(pedido_id,created_at desc);
create index if not exists idx_order_dispatch_items_dispatch on public.order_dispatch_items(dispatch_id);
create index if not exists idx_order_dispatch_items_pedido_item on public.order_dispatch_items(pedido_item_id);
alter table public.order_dispatches enable row level security;
alter table public.order_dispatch_items enable row level security;
grant select on public.order_dispatches,public.order_dispatch_items to authenticated;

-- Store alternatives --------------------------------------------------------
create table if not exists public.order_alternatives(
  id bigint generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id) on delete cascade,
  pedido_item_id integer not null references public.pedido_items(id) on delete cascade,
  alternative_material_id integer not null references public.materiales(id) on delete restrict,
  proposed_by uuid not null references public.profiles(id) on delete restrict,
  reason text,
  status text not null default 'pending' check(status=any(array['pending'::text,'approved'::text,'rejected'::text])),
  decided_by uuid references public.profiles(id) on delete set null,
  decision_note text,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);
create index if not exists idx_order_alternatives_order on public.order_alternatives(pedido_id,status);
create index if not exists idx_order_alternatives_item on public.order_alternatives(pedido_item_id);
alter table public.order_alternatives enable row level security;
grant select on public.order_alternatives to authenticated;

-- Activity history ----------------------------------------------------------
create table if not exists public.order_activity(
  id bigint generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_order_activity_order on public.order_activity(pedido_id,created_at desc);
alter table public.order_activity enable row level security;
grant select on public.order_activity to authenticated;
grant usage,select on sequence public.materiales_id_seq to authenticated;

-- Access helpers ------------------------------------------------------------
create or replace function public.is_active_supervisor()
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='supervisor' and status='activo');
$$;
create or replace function public.is_active_store()
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='store' and status='activo');
$$;
create or replace function public.is_active_worker()
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='encargado' and status='activo');
$$;
create or replace function public.supervisor_has_project(p_project_id integer)
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(
    select 1 from public.project_members pm
    join public.profiles p on p.id=pm.user_id
    where pm.user_id=auth.uid() and pm.project_id=p_project_id and p.role='supervisor' and p.status='activo'
  );
$$;
create or replace function public.can_view_order_v2(p_order_id integer)
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from public.pedidos o where o.id=p_order_id and (
    public.is_active_admin()
    or (public.is_active_worker() and o.user_id=auth.uid())
    or (public.is_active_supervisor() and public.supervisor_has_project(o.project_id))
    or (public.is_active_store() and o.status in ('approved','awaiting_receipt','partial','completed','delivered'))
  ));
$$;

grant execute on function public.is_active_supervisor() to authenticated;
grant execute on function public.is_active_store() to authenticated;
grant execute on function public.is_active_worker() to authenticated;
grant execute on function public.supervisor_has_project(integer) to authenticated;
grant execute on function public.can_view_order_v2(integer) to authenticated;

-- RLS -----------------------------------------------------------------------
drop policy if exists project_members_select on public.project_members;
drop policy if exists project_members_insert_admin on public.project_members;
drop policy if exists project_members_delete_admin on public.project_members;
create policy project_members_select on public.project_members for select to authenticated using(user_id=(select auth.uid()) or public.is_active_admin());
create policy project_members_insert_admin on public.project_members for insert to authenticated with check(public.is_active_admin());
create policy project_members_delete_admin on public.project_members for delete to authenticated using(public.is_active_admin());

drop policy if exists pedidos_select_own_or_admin on public.pedidos;
drop policy if exists pedidos_select_workflow_v2 on public.pedidos;
create policy pedidos_select_workflow_v2 on public.pedidos for select to authenticated using(
  public.is_active_admin()
  or (public.is_active_worker() and user_id=(select auth.uid()))
  or (public.is_active_supervisor() and public.supervisor_has_project(project_id))
  or (public.is_active_store() and status in ('approved','awaiting_receipt','partial','completed','delivered'))
);

drop policy if exists pedido_items_select_own_or_admin on public.pedido_items;
drop policy if exists pedido_items_select_workflow_v2 on public.pedido_items;
create policy pedido_items_select_workflow_v2 on public.pedido_items for select to authenticated using(public.can_view_order_v2(pedido_id));

drop policy if exists order_dispatches_select_workflow on public.order_dispatches;
create policy order_dispatches_select_workflow on public.order_dispatches for select to authenticated using(public.can_view_order_v2(pedido_id));
drop policy if exists order_dispatch_items_select_workflow on public.order_dispatch_items;
create policy order_dispatch_items_select_workflow on public.order_dispatch_items for select to authenticated using(
  exists(select 1 from public.order_dispatches d where d.id=order_dispatch_items.dispatch_id and public.can_view_order_v2(d.pedido_id))
);
drop policy if exists order_alternatives_select_workflow on public.order_alternatives;
create policy order_alternatives_select_workflow on public.order_alternatives for select to authenticated using(public.can_view_order_v2(pedido_id));
drop policy if exists order_activity_select_workflow on public.order_activity;
create policy order_activity_select_workflow on public.order_activity for select to authenticated using(public.can_view_order_v2(pedido_id));

drop policy if exists materiales_insert_admin on public.materiales;
drop policy if exists materiales_insert_store on public.materiales;
drop policy if exists materiales_insert_admin_or_store on public.materiales;
create policy materiales_insert_admin_or_store on public.materiales for insert to authenticated with check(public.is_active_admin() or public.is_active_store());

drop policy if exists material_images_insert_store on storage.objects;
create policy material_images_insert_store on storage.objects for insert to authenticated with check(bucket_id='material-images' and public.is_active_store());
drop policy if exists material_images_select_store on storage.objects;
create policy material_images_select_store on storage.objects for select to authenticated using(bucket_id='material-images' and public.is_active_store());

-- Receiver list -------------------------------------------------------------
create or replace function public.list_request_receivers_v2(p_project_id integer)
returns table(id uuid,full_name text,"position" text,department text)
language plpgsql stable security definer set search_path to '' as $$
begin
  if not public.is_active_user() then raise exception using errcode='42501',message='Active user required.'; end if;
  if public.is_active_supervisor() and not public.supervisor_has_project(p_project_id) then raise exception using errcode='42501',message='You are not assigned to this project.'; end if;
  if not(public.is_active_supervisor() or public.is_active_admin()) then raise exception using errcode='42501',message='Only supervisors or administrators can select another receiver.'; end if;
  return query select p.id,p.full_name,p.position,p.department from public.profiles p
    where p.status='activo' and p.role in ('encargado','supervisor') order by p.full_name nulls last;
end;
$$;
grant execute on function public.list_request_receivers_v2(integer) to authenticated;

-- Create request ------------------------------------------------------------
create or replace function public.create_material_request_v2(
  p_project_id integer,p_notes text default null,p_urgency text default 'normal',p_delivery_date date default null,
  p_supplier text default null,p_delivery_location text default null,p_items jsonb default '[]'::jsonb,p_requested_for uuid default null
) returns jsonb language plpgsql security definer set search_path to '' as $$
declare
  v_actor_id uuid:=auth.uid(); v_actor public.profiles%rowtype; v_receiver public.profiles%rowtype;
  v_project public.proyectos%rowtype; v_settings public.app_settings%rowtype; v_receiver_id uuid;
  v_requester_sequence integer; v_project_sequence integer; v_order_number text; v_document_name text;
  v_supplier text; v_delivery_location text; v_order_id integer; v_item_count integer;
begin
  if v_actor_id is null then raise exception using errcode='42501',message='Authentication required.'; end if;
  select * into v_actor from public.profiles where id=v_actor_id;
  if not found or v_actor.status<>'activo' or v_actor.role='store' then raise exception using errcode='42501',message='This user cannot create material requests.'; end if;
  if v_actor.role='encargado' then v_receiver_id:=v_actor_id; else v_receiver_id:=coalesce(p_requested_for,v_actor_id); end if;
  select * into v_receiver from public.profiles where id=v_receiver_id and status='activo';
  if not found or v_receiver.role='store' then raise exception using errcode='22023',message='Invalid receiver.'; end if;
  select * into v_project from public.proyectos where id=p_project_id and estado='activo';
  if not found then raise exception using errcode='22023',message='The selected project is not active.'; end if;
  if v_actor.role='supervisor' and not public.supervisor_has_project(p_project_id) then raise exception using errcode='42501',message='You are not assigned to this project.'; end if;
  if v_receiver.document_initials is null or btrim(v_receiver.document_initials)='' then raise exception using errcode='22023',message='Document initials are not configured for the receiver.'; end if;
  select * into v_settings from public.app_settings where id=1;
  if not found then raise exception using errcode='55000',message='Application settings are missing.'; end if;
  p_urgency:=lower(coalesce(nullif(btrim(p_urgency),''),'normal'));
  if p_urgency not in ('normal','urgent','critical') then raise exception using errcode='22023',message='Invalid urgency.'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception using errcode='22023',message='At least one material is required.'; end if;
  if exists(select 1 from jsonb_array_elements(p_items) x where not(x?'material_id') or not(x?'cantidad') or coalesce(x->>'material_id','')!~'^[0-9]+$' or coalesce(x->>'cantidad','')!~'^[0-9]+([.][0-9]+)?$' or (x->>'cantidad')::numeric<=0) then raise exception using errcode='22023',message='One or more material lines are invalid.'; end if;
  if exists(select 1 from jsonb_array_elements(p_items) x group by (x->>'material_id')::integer having count(*)>1) then raise exception using errcode='22023',message='The same material cannot be added twice.'; end if;
  select count(*) into v_item_count from jsonb_array_elements(p_items) x join public.materiales m on m.id=(x->>'material_id')::integer;
  if v_item_count<>jsonb_array_length(p_items) then raise exception using errcode='23503',message='One or more materials no longer exist.'; end if;

  insert into public.requester_order_counters(user_id,next_number) values(v_receiver_id,1) on conflict(user_id) do nothing;
  select next_number into v_requester_sequence from public.requester_order_counters where user_id=v_receiver_id for update;
  insert into public.project_requester_counters(project_id,user_id,next_number) values(p_project_id,v_receiver_id,1) on conflict(project_id,user_id) do nothing;
  select next_number into v_project_sequence from public.project_requester_counters where project_id=p_project_id and user_id=v_receiver_id for update;

  v_order_number:=upper(btrim(v_settings.company_initials))||coalesce(v_settings.order_separator,'-')||upper(btrim(v_receiver.document_initials))||coalesce(v_settings.order_separator,'-')||v_requester_sequence::text;
  v_document_name:=coalesce(nullif(btrim(v_settings.document_title),''),'MATERIAL REQUEST')||coalesce(v_settings.document_separator,' - ')||upper(btrim(v_project.codigo))||coalesce(v_settings.document_separator,' - ')||upper(btrim(v_receiver.document_initials))||coalesce(v_settings.document_separator,' - ')||lpad(v_project_sequence::text,coalesce(v_settings.project_sequence_padding,2),'0');
  v_supplier:=coalesce(nullif(btrim(p_supplier),''),nullif(btrim(v_project.default_supplier),''),nullif(btrim(v_settings.default_supplier),''));
  v_delivery_location:=coalesce(nullif(btrim(p_delivery_location),''),nullif(btrim(v_project.default_delivery_location),''),nullif(btrim(v_settings.default_delivery_location),''));

  insert into public.pedidos(user_id,requested_for,created_by,created_by_name_snapshot,project_id,status,urgencia,delivery_date,notas,order_number,requester_sequence,document_name,project_sequence,company_initials_snapshot,requester_initials_snapshot,project_name_snapshot,project_code_snapshot,requested_by_name,requested_by_email,requested_by_position,requested_by_department,requested_by_employee_code,supplier,delivery_location)
  values(v_receiver_id,v_receiver_id,v_actor_id,v_actor.full_name,p_project_id,'pending',p_urgency,p_delivery_date,nullif(btrim(p_notes),''),v_order_number,v_requester_sequence,v_document_name,v_project_sequence,upper(btrim(v_settings.company_initials)),upper(btrim(v_receiver.document_initials)),v_project.nombre,v_project.codigo,v_receiver.full_name,v_receiver.email,v_receiver.position,v_receiver.department,v_receiver.employee_code,v_supplier,v_delivery_location)
  returning id into v_order_id;

  insert into public.pedido_items(pedido_id,material_id,cantidad,notas,line_number,material_code_snapshot,material_name_snapshot,description_snapshot,unit_snapshot,supplier,quantity_delivered,quantity_received,required_date,observation)
  select v_order_id,m.id,(x.value->>'cantidad')::numeric,coalesce(x.value->>'notas',''),x.ordinality::integer,m.id_material,m.nombre,m.descripcion,m.unidad_medida,coalesce(nullif(btrim(x.value->>'supplier'),''),v_supplier),0,0,coalesce(nullif(x.value->>'required_date','')::date,p_delivery_date),coalesce(nullif(btrim(x.value->>'observation'),''),nullif(btrim(x.value->>'notas'),''))
  from jsonb_array_elements(p_items) with ordinality x(value,ordinality) join public.materiales m on m.id=(x.value->>'material_id')::integer;

  update public.requester_order_counters set next_number=v_requester_sequence+1 where user_id=v_receiver_id;
  update public.project_requester_counters set next_number=v_project_sequence+1 where project_id=p_project_id and user_id=v_receiver_id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(v_order_id,v_actor_id,'created',jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'User')||' created the material request.'));
  return jsonb_build_object('id',v_order_id,'order_number',v_order_number,'document_name',v_document_name,'status','pending');
end;
$$;
grant execute on function public.create_material_request_v2(integer,text,text,date,text,text,jsonb,uuid) to authenticated;

-- Edit request before first dispatch ----------------------------------------
create or replace function public.update_material_request_v2(p_order_id integer,p_project_id integer,p_requested_for uuid,p_notes text,p_urgency text,p_delivery_date date,p_items jsonb)
returns jsonb language plpgsql security definer set search_path to '' as $$
declare v_actor public.profiles%rowtype; v_order public.pedidos%rowtype; v_allowed boolean:=false;
begin
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  if not found then raise exception using errcode='42501',message='Active user required.'; end if;
  select * into v_order from public.pedidos where id=p_order_id for update;
  if not found then raise exception using errcode='P0002',message='Order not found.'; end if;
  if exists(select 1 from public.order_dispatches where pedido_id=p_order_id) then raise exception using errcode='22023',message='The order cannot be edited after Store has dispatched material.'; end if;
  if p_project_id<>v_order.project_id or p_requested_for<>v_order.user_id then raise exception using errcode='22023',message='Project and receiver cannot be changed after the order number has been assigned.'; end if;
  if v_actor.role='encargado' then v_allowed:=(v_order.user_id=auth.uid() and v_order.status='pending');
  elsif v_actor.role='supervisor' then v_allowed:=(v_order.status in ('pending','approved') and public.supervisor_has_project(v_order.project_id));
  elsif v_actor.role='admin' then v_allowed:=v_order.status in ('pending','approved'); end if;
  if not v_allowed then raise exception using errcode='42501',message='You cannot edit this order.'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception using errcode='22023',message='At least one material is required.'; end if;
  update public.pedidos set urgencia=lower(coalesce(nullif(btrim(p_urgency),''),'normal')),delivery_date=p_delivery_date,notas=nullif(btrim(p_notes),'') where id=p_order_id;
  delete from public.pedido_items where pedido_id=p_order_id;
  insert into public.pedido_items(pedido_id,material_id,cantidad,notas,line_number,material_code_snapshot,material_name_snapshot,description_snapshot,unit_snapshot,quantity_delivered,quantity_received,required_date,observation)
  select p_order_id,m.id,(x.value->>'cantidad')::numeric,coalesce(x.value->>'notas',''),x.ordinality::integer,m.id_material,m.nombre,m.descripcion,m.unidad_medida,0,0,p_delivery_date,nullif(btrim(x.value->>'notas'),'')
  from jsonb_array_elements(p_items) with ordinality x(value,ordinality) join public.materiales m on m.id=(x.value->>'material_id')::integer;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(p_order_id,auth.uid(),'updated',jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'User')||' edited the material request.'));
  return jsonb_build_object('id',p_order_id,'status',v_order.status);
end;
$$;
grant execute on function public.update_material_request_v2(integer,integer,uuid,text,text,date,jsonb) to authenticated;

-- Approval / rejection ------------------------------------------------------
create or replace function public.approve_material_request_v2(p_order_id integer)
returns void language plpgsql security definer set search_path to '' as $$
declare v_order public.pedidos%rowtype; v_actor public.profiles%rowtype;
begin
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  select * into v_order from public.pedidos where id=p_order_id for update;
  if not found then raise exception using errcode='P0002',message='Order not found.'; end if;
  if not(v_actor.role='admin' or (v_actor.role='supervisor' and public.supervisor_has_project(v_order.project_id))) then raise exception using errcode='42501',message='Only the project supervisor or an administrator can approve this order.'; end if;
  if v_order.status<>'pending' then raise exception using errcode='22023',message='Only pending orders can be approved.'; end if;
  update public.pedidos set status='approved',approved_by=auth.uid(),approved_at=now() where id=p_order_id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(p_order_id,auth.uid(),'approved',jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'Supervisor')||' approved the order.'));
end;
$$;
grant execute on function public.approve_material_request_v2(integer) to authenticated;

create or replace function public.reject_material_request_v2(p_order_id integer,p_reason text default null)
returns void language plpgsql security definer set search_path to '' as $$
declare v_order public.pedidos%rowtype; v_actor public.profiles%rowtype;
begin
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  select * into v_order from public.pedidos where id=p_order_id for update;
  if not found then raise exception using errcode='P0002',message='Order not found.'; end if;
  if not(v_actor.role='admin' or (v_actor.role='supervisor' and public.supervisor_has_project(v_order.project_id))) then raise exception using errcode='42501',message='Only the project supervisor or an administrator can reject this order.'; end if;
  if v_order.status not in ('pending','approved') or exists(select 1 from public.order_dispatches where pedido_id=p_order_id) then raise exception using errcode='22023',message='This order can no longer be rejected.'; end if;
  update public.pedidos set status='rejected',rejected_reason=nullif(btrim(p_reason),'') where id=p_order_id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(p_order_id,auth.uid(),'rejected',jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'Supervisor')||' rejected the order.','reason',p_reason));
end;
$$;
grant execute on function public.reject_material_request_v2(integer,text) to authenticated;

-- Alternatives --------------------------------------------------------------
create or replace function public.propose_alternative_v2(p_order_id integer,p_pedido_item_id integer,p_alternative_material_id integer,p_reason text default null)
returns bigint language plpgsql security definer set search_path to '' as $$
declare v_actor public.profiles%rowtype; v_order public.pedidos%rowtype; v_id bigint; v_alt_name text;
begin
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  if not found or v_actor.role not in ('store','admin') then raise exception using errcode='42501',message='Only Store or an administrator can propose alternatives.'; end if;
  select * into v_order from public.pedidos where id=p_order_id;
  if not found or v_order.status not in ('approved','partial') then raise exception using errcode='22023',message='Alternatives can only be proposed for approved or partial orders.'; end if;
  if not exists(select 1 from public.pedido_items where id=p_pedido_item_id and pedido_id=p_order_id) then raise exception using errcode='22023',message='Invalid order item.'; end if;
  select nombre into v_alt_name from public.materiales where id=p_alternative_material_id;
  if not found then raise exception using errcode='23503',message='Alternative material not found.'; end if;
  update public.order_alternatives set status='rejected',decided_at=now(),decision_note='Superseded by newer proposal' where pedido_item_id=p_pedido_item_id and status='pending';
  insert into public.order_alternatives(pedido_id,pedido_item_id,alternative_material_id,proposed_by,reason) values(p_order_id,p_pedido_item_id,p_alternative_material_id,auth.uid(),nullif(btrim(p_reason),'')) returning id into v_id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(p_order_id,auth.uid(),'alternative_proposed',jsonb_build_object('actor_name',v_actor.full_name,'message','Store proposed alternative: '||v_alt_name));
  return v_id;
end;
$$;
grant execute on function public.propose_alternative_v2(integer,integer,integer,text) to authenticated;

create or replace function public.decide_alternative_v2(p_alternative_id bigint,p_decision text,p_note text default null)
returns void language plpgsql security definer set search_path to '' as $$
declare v_alt public.order_alternatives%rowtype; v_order public.pedidos%rowtype; v_actor public.profiles%rowtype; v_name text;
begin
  if p_decision not in ('approved','rejected') then raise exception using errcode='22023',message='Decision must be approved or rejected.'; end if;
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  select * into v_alt from public.order_alternatives where id=p_alternative_id for update;
  if not found then raise exception using errcode='P0002',message='Alternative not found.'; end if;
  select * into v_order from public.pedidos where id=v_alt.pedido_id;
  if not(v_actor.role='admin' or (v_actor.role='supervisor' and public.supervisor_has_project(v_order.project_id))) then raise exception using errcode='42501',message='Only the project supervisor or an administrator can decide this alternative.'; end if;
  if v_alt.status<>'pending' then raise exception using errcode='22023',message='This alternative has already been decided.'; end if;
  update public.order_alternatives set status=p_decision,decided_by=auth.uid(),decision_note=nullif(btrim(p_note),''),decided_at=now() where id=p_alternative_id;
  select nombre into v_name from public.materiales where id=v_alt.alternative_material_id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(v_alt.pedido_id,auth.uid(),'alternative_'||p_decision,jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'Supervisor')||' '||p_decision||' alternative '||coalesce(v_name,'')));
end;
$$;
grant execute on function public.decide_alternative_v2(bigint,text,text) to authenticated;

-- Store dispatch ------------------------------------------------------------
create or replace function public.dispatch_material_request_v2(p_order_id integer,p_note text,p_items jsonb)
returns bigint language plpgsql security definer set search_path to '' as $$
declare v_actor public.profiles%rowtype; v_order public.pedidos%rowtype; v_dispatch_id bigint; v_line jsonb; v_item public.pedido_items%rowtype; v_qty numeric; v_actual_material integer; v_outstanding numeric;
begin
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  if not found or v_actor.role not in ('store','admin') then raise exception using errcode='42501',message='Only Store or an administrator can dispatch materials.'; end if;
  select * into v_order from public.pedidos where id=p_order_id for update;
  if not found then raise exception using errcode='P0002',message='Order not found.'; end if;
  if v_order.status not in ('approved','partial') then raise exception using errcode='22023',message='This order is not ready for dispatch.'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception using errcode='22023',message='At least one dispatch quantity is required.'; end if;
  if exists(select 1 from jsonb_array_elements(p_items) x group by (x->>'pedido_item_id')::integer having count(*)>1) then raise exception using errcode='22023',message='Each order item can appear only once in a dispatch.'; end if;
  insert into public.order_dispatches(pedido_id,dispatched_by,note) values(p_order_id,auth.uid(),nullif(btrim(p_note),'')) returning id into v_dispatch_id;
  for v_line in select value from jsonb_array_elements(p_items) loop
    select * into v_item from public.pedido_items where id=(v_line->>'pedido_item_id')::integer and pedido_id=p_order_id for update;
    if not found then raise exception using errcode='22023',message='Invalid dispatch item.'; end if;
    v_qty:=(v_line->>'quantity')::numeric;
    if v_qty<=0 then raise exception using errcode='22023',message='Dispatch quantities must be greater than zero.'; end if;
    v_outstanding:=greatest(0,v_item.cantidad-v_item.quantity_received);
    if v_qty>v_outstanding then raise exception using errcode='22023',message='Dispatch quantity exceeds outstanding requested quantity.'; end if;
    v_actual_material:=coalesce(nullif(v_line->>'material_id','')::integer,v_item.material_id);
    if v_actual_material<>v_item.material_id and not exists(select 1 from public.order_alternatives a where a.pedido_item_id=v_item.id and a.alternative_material_id=v_actual_material and a.status='approved') then raise exception using errcode='22023',message='The selected alternative has not been approved.'; end if;
    insert into public.order_dispatch_items(dispatch_id,pedido_item_id,material_id,quantity_dispatched) values(v_dispatch_id,v_item.id,v_actual_material,v_qty);
    update public.pedido_items set quantity_delivered=quantity_delivered+v_qty where id=v_item.id;
  end loop;
  update public.pedidos set status='awaiting_receipt' where id=p_order_id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(p_order_id,auth.uid(),'dispatched',jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'Store')||' dispatched materials.','dispatch_id',v_dispatch_id));
  return v_dispatch_id;
end;
$$;
grant execute on function public.dispatch_material_request_v2(integer,text,jsonb) to authenticated;

-- Worker / Supervisor receipt ----------------------------------------------
create or replace function public.confirm_dispatch_receipt_v2(p_dispatch_id bigint,p_items jsonb)
returns text language plpgsql security definer set search_path to '' as $$
declare v_actor public.profiles%rowtype; v_dispatch public.order_dispatches%rowtype; v_order public.pedidos%rowtype; v_line jsonb; v_di public.order_dispatch_items%rowtype; v_qty numeric; v_status text; v_all_complete boolean;
begin
  select * into v_actor from public.profiles where id=auth.uid() and status='activo';
  if not found or v_actor.role not in ('encargado','supervisor') then raise exception using errcode='42501',message='Only the receiving worker or project supervisor can confirm receipt.'; end if;
  select * into v_dispatch from public.order_dispatches where id=p_dispatch_id for update;
  if not found then raise exception using errcode='P0002',message='Dispatch not found.'; end if;
  if v_dispatch.receipt_confirmed_at is not null then raise exception using errcode='22023',message='This dispatch has already been confirmed.'; end if;
  select * into v_order from public.pedidos where id=v_dispatch.pedido_id for update;
  if v_actor.role='encargado' and v_order.user_id<>auth.uid() then raise exception using errcode='42501',message='Only the worker assigned to this request can confirm it.'; end if;
  if v_actor.role='supervisor' and not public.supervisor_has_project(v_order.project_id) then raise exception using errcode='42501',message='You are not assigned to this project.'; end if;
  if v_order.status<>'awaiting_receipt' then raise exception using errcode='22023',message='This order is not awaiting receipt.'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' then raise exception using errcode='22023',message='Receipt lines are required.'; end if;
  if jsonb_array_length(p_items)<>(select count(*) from public.order_dispatch_items where dispatch_id=p_dispatch_id) then raise exception using errcode='22023',message='All dispatched lines must be confirmed together.'; end if;
  if exists(select 1 from jsonb_array_elements(p_items) x group by (x->>'dispatch_item_id')::bigint having count(*)>1) then raise exception using errcode='22023',message='A receipt line cannot be repeated.'; end if;
  for v_line in select value from jsonb_array_elements(p_items) loop
    select * into v_di from public.order_dispatch_items where id=(v_line->>'dispatch_item_id')::bigint and dispatch_id=p_dispatch_id for update;
    if not found then raise exception using errcode='22023',message='Invalid receipt line.'; end if;
    v_qty:=(v_line->>'quantity_received')::numeric;
    if v_qty<0 or v_qty>v_di.quantity_dispatched then raise exception using errcode='22023',message='Received quantity must be between zero and dispatched quantity.'; end if;
    update public.order_dispatch_items set quantity_received=v_qty,receipt_observation=nullif(btrim(v_line->>'observation'),''),received_by=auth.uid(),received_at=now() where id=v_di.id;
  end loop;
  update public.order_dispatches set receipt_confirmed_by=auth.uid(),receipt_confirmed_at=now() where id=p_dispatch_id;
  update public.pedido_items pi set quantity_received=coalesce((select sum(di.quantity_received) from public.order_dispatch_items di join public.order_dispatches d on d.id=di.dispatch_id where di.pedido_item_id=pi.id and d.receipt_confirmed_at is not null),0),received_by=auth.uid(),received_at=now() where pi.pedido_id=v_order.id;
  select bool_and(quantity_received>=cantidad) into v_all_complete from public.pedido_items where pedido_id=v_order.id;
  v_status:=case when coalesce(v_all_complete,false) then 'completed' else 'partial' end;
  update public.pedidos set status=v_status,receipt_confirmed_by=case when v_status='completed' then auth.uid() else receipt_confirmed_by end,receipt_confirmed_at=case when v_status='completed' then now() else receipt_confirmed_at end where id=v_order.id;
  insert into public.order_activity(pedido_id,actor_id,action,details) values(v_order.id,auth.uid(),'receipt_confirmed',jsonb_build_object('actor_name',v_actor.full_name,'message',coalesce(v_actor.full_name,'Receiver')||' confirmed the material receipt.','dispatch_id',p_dispatch_id,'result',v_status));
  if v_status='completed' then insert into public.order_activity(pedido_id,actor_id,action,details) values(v_order.id,auth.uid(),'completed',jsonb_build_object('actor_name',v_actor.full_name,'message','Order completed: all requested quantities have been received.')); end if;
  return v_status;
end;
$$;
grant execute on function public.confirm_dispatch_receipt_v2(bigint,jsonb) to authenticated;

-- Security hardening --------------------------------------------------------
revoke execute on function public.approve_material_request_v2(integer) from public, anon;
revoke execute on function public.can_view_order_v2(integer) from public, anon;
revoke execute on function public.confirm_dispatch_receipt_v2(bigint,jsonb) from public, anon;
revoke execute on function public.create_material_request_v2(integer,text,text,date,text,text,jsonb,uuid) from public, anon;
revoke execute on function public.decide_alternative_v2(bigint,text,text) from public, anon;
revoke execute on function public.dispatch_material_request_v2(integer,text,jsonb) from public, anon;
revoke execute on function public.is_active_store() from public, anon;
revoke execute on function public.is_active_supervisor() from public, anon;
revoke execute on function public.is_active_worker() from public, anon;
revoke execute on function public.list_request_receivers_v2(integer) from public, anon;
revoke execute on function public.propose_alternative_v2(integer,integer,integer,text) from public, anon;
revoke execute on function public.reject_material_request_v2(integer,text) from public, anon;
revoke execute on function public.supervisor_has_project(integer) from public, anon;
revoke execute on function public.update_material_request_v2(integer,integer,uuid,text,text,date,jsonb) from public, anon;

-- Performance indexes -------------------------------------------------------
create index if not exists idx_order_activity_actor_id on public.order_activity(actor_id);
create index if not exists idx_order_alternatives_material_id on public.order_alternatives(alternative_material_id);
create index if not exists idx_order_alternatives_decided_by on public.order_alternatives(decided_by);
create index if not exists idx_order_alternatives_proposed_by on public.order_alternatives(proposed_by);
create index if not exists idx_order_dispatch_items_material_id on public.order_dispatch_items(material_id);
create index if not exists idx_order_dispatch_items_received_by on public.order_dispatch_items(received_by);
create index if not exists idx_order_dispatches_dispatched_by on public.order_dispatches(dispatched_by);
create index if not exists idx_order_dispatches_receipt_confirmed_by on public.order_dispatches(receipt_confirmed_by);
create index if not exists idx_pedido_items_received_by on public.pedido_items(received_by);
create index if not exists idx_pedidos_created_by on public.pedidos(created_by);
create index if not exists idx_pedidos_requested_for on public.pedidos(requested_for);
create index if not exists idx_pedidos_receipt_confirmed_by on public.pedidos(receipt_confirmed_by);

commit;
